database_name = "starwars"
people_collection_name = "characters"
starship_collection_name = "starships"
people_url_base = "https://swapi.dev/api/people/"
starships_url_base = "https://swapi.dev/api/starships/"
connection_url = "mongodb://localhost:27017/"
